version: '3'
services:
  app:
    build:
      context: .
      target: production  # Use the production stage from the Dockerfile
    container_name: nestjs-app-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: node dist/main  # Run the built app in production mode
