version: '3'
services:
  app:
    build:
      context: .
      target: development  # Use the development stage from the Dockerfile
    container_name: nestjs-app-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app  # Mount your project directory into the container
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev  # Start in dev mode with hot-reloading
